### PR TITLE
api for assigning a separate mask file

### PR DESCRIPTION
**Pull request by chuckie82**
API for assigning a separate mask file. Keyword: maskfile
This allows to use a static mask generated by psocake for indexing.

### CODE REVIEW

**Comment by tjlane** [comment]
seems reasonable, but needs documentation

**Comment by chuckie82** [comment]
Added documentation for maskfile

**Comment by tjlane** [comment]
I changed the doc to have correct units (micron vs. meters). This is good to pull in -- if you agree do it.

**Comment by chuckie82** [comment]
Agreed.

**Pull request merged**
