### PR TITLE
Newdets

### PR DESCRIPTION
**Pull request by tjlane**
New detectors pull request. I think this is good to go.
- support for rayonix
- support for pnccd

@chrisvam @chuckie82 please review.

### CODE REVIEW

**Comment by tjlane** [comment]
So not in this, which (upon reflection) probably should be added before merge:
- crystFEL read/write
- tests of the crystFEL read/write

**Comment by tjlane** [comment]
This PR aims to address #10 

Currently done:
- rayonix

To be completed soon:
- pnCCD
- ePix

**Comment by tjlane** [comment]
@chuckie82 coffset changes merged here
resolves #16

**Comment by chuckie82** [comment]
OK, thanks.
Could you show me an example for translate(0,0,Z) that I should be using?

**Comment by tjlane** [comment]
Super simple:

```
from psgeom import camera
g = camera.Cspad.from_psana_file('ref_files/refgeom_psana.data')
print g.xyz
g.translate((0,0,-100000))
print g.xyz
```

**Comment by chuckie82** [comment]
I'll add a test for translate roundtrip.

**Comment by chuckie82** [comment]
@tjlane Let's merge this PR. 
It will be easier for me to test out newdets and distance all in one.

**Comment by tjlane** [comment]
@chuckie82 sorry for the delayed response. I think we can do this. For my records, to be implemented:
- ePix100
- pnCCD

**Pull request merged**
